# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.9.0

pipelines:
  default:
    - step:
        name: Migrations and test (look at postinstall script)
        caches:
          - node
        script:
          - yarn install
          - yarn test:cov
        services:
          - postgres
  branches:
    master:
      - step:
          name: Tests one more time before deploy
          caches:
            - node
          script:
            - yarn install
            - yarn test:cov
          services:
            - postgres
      - step:
          name: Deploy to altiore-staging
          deployment: staging
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: 'pipelines'
        POSTGRES_USER: 'test_user'
        POSTGRES_PASSWORD: 'test_user_password'
