image: node:12.14.0

pipelines:
  default:
    - step:
        name: Migrations and test (look at postinstall script)
        deployment: test
        caches:
          - node
        script:
          - npm ci
          - npm run build
          - npm run test:remote
        services:
          - postgres
          - redis
  branches:
    staging:
      - step:
          name: Staging build
          caches:
            - node
          script:
            - npm ci
            - npm run build
          services:
            - postgres
            - redis
          artifacts: # defining the artifacts to be passed to each future step.
            - dist/**
            - node_modules/**
      - step:
          name: Staging tests
          caches:
            - node
          script:
            - npm run test:remote
          services:
            - postgres
            - redis
      - step:
          name: Staging DEPLOY
          deployment: staging
          script:
            - cd heroku
            - rm -rf bin
            - rm -rf dist
            - rm -rf .git
            - rm -rf mails
            - rm -rf package.json
            - rm -rf package-lock.json
            - cp -r ../bin ./bin
            - cp -r ../dist ./dist
            - cp -r ../mails ./mails
            - cp ../ormconfig.js ./ormconfig.js
            - cp ../package.json ./package.json
            - sed "s/rm -rf dist && tsc/echo NO NEED BUILD PREFERATION/" -i package.json
            - cp ../package-lock.json ./package-lock.json
            - git init
            - git add .
            - git config user.email "razvanlomov@gmail.com"
            - git config user.name "bitbucket-pipelines"
            - git commit -m 'dynamic version'
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$STAGING_APP_NAME.git -f HEAD:master
    master:
      - step:
          name: Production build
          caches:
            - node
          script:
            - npm ci
            - npm run build
          services:
            - postgres
            - redis
          artifacts: # defining the artifacts to be passed to each future step.
            - dist/**
            - node_modules/**
      - step:
          name: Production tests
          caches:
            - node
          script:
            - npm run test:remote
          services:
            - postgres
            - redis
      - step:
          name: Production DEPLOY
          deployment: production
          script:
            - cd heroku
            - rm -rf bin
            - rm -rf dist
            - rm -rf .git
            - rm -rf mails
            - rm -rf package.json
            - rm -rf package-lock.json
            - cp -r ../bin ./bin
            - cp -r ../dist ./dist
            - cp -r ../mails ./mails
            - cp ../ormconfig.js ./ormconfig.js
            - cp ../package.json ./package.json
            - sed "s/rm -rf dist && tsc/echo NO NEED BUILD PREFERATION/" -i package.json
            - cp ../package-lock.json ./package-lock.json
            - git init
            - git add .
            - git config user.email "razvanlomov@gmail.com"
            - git config user.name "bitbucket-pipelines"
            - git commit -m 'dynamic version'
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$PRODUCTION_APP_NAME.git -f HEAD:master

definitions:
  services:
    postgres:
      image: postgres:11.5
      restart: always
      volumes:
        - ./docker/postgres-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        - ./docker/wait-postgres.sh:/usr/bin/wait-postgres
      environment:
        POSTGRES_DB: 'pipelines'
        POSTGRES_USER: 'test_user'
        POSTGRES_PASSWORD: 'test_user_password'
    redis:
      image: redis
