image: node:8.12.0

pipelines:
  default:
    - step:
        name: Migrations and test (look at postinstall script)
        deployment: test
        caches:
          - node
        script:
          - npm i
          - npm run build
          - npm run test:remote
        services:
          - postgres
          - redis
  branches:
    staging:
      - step:
          name: Tests one more time before deploy
          caches:
            - node
          script:
            - npm i
            - npm run build
            - npm run test:remote
          services:
            - postgres
            - redis
      - step:
          name: Deploy to altiore-staging
          deployment: staging
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git -f HEAD:master
    master:
      - step:
          name: Tests one more time before deploy
          deployment: production
          caches:
            - node
          script:
            - npm i
            - npm run build
            - npm run test:remote
          services:
            - postgres
            - redis

definitions:
  services:
    postgres:
      image: postgres:11.5
      restart: always
      volumes:
        - ./docker/postgres-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        - ./docker/wait-postgres.sh:/usr/bin/wait-postgres
      environment:
        POSTGRES_DB: 'pipelines'
        POSTGRES_USER: 'test_user'
        POSTGRES_PASSWORD: 'test_user_password'
    redis:
      image: redis
