image: node:8.11.3

pipelines:
  default:
    - step:
        name: Migrations and test (look at postinstall script)
        deployment: test
        caches:
          - node
        script:
          - yarn install
          - yarn test:remote
        services:
          - postgres
  branches:
    staging:
      - step:
          name: Tests one more time before deploy
          caches:
            - node
          script:
            - yarn install
            - yarn test:remote
          services:
            - postgres
      - step:
          name: Deploy to altiore-staging
          deployment: staging
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
    master:
      - step:
          name: Tests one more time before deploy
          deployment: production
          caches:
            - node
          script:
            - yarn install
            - yarn test:remote
          services:
            - postgres

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: 'pipelines'
        POSTGRES_USER: 'test_user'
        POSTGRES_PASSWORD: 'test_user_password'
