version: '3'

services:
  redis:
    image: redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - ${REDIS_PORT}:6379

  postgres:
    image: postgres:11.6
    restart: always
    volumes:
      - ./docker/postgres-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/wait-postgres.sh:/usr/bin/wait-postgres
    environment:
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - POSTGRES_TEST_DB=${POSTGRES_TEST_DB}
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
    ports:
      - ${TYPEORM_PORT}:5432

volumes:
  postgres:
    driver: local
  redis:
    driver: local
