version: '3'

services:
  redis:
    image: redis
    container_name: altiore_cache
    volumes:
      - redis-altiore:/data
    ports:
      - ${REDIS_PORT}:6379
    expose:
      - 6379

  postgres:
    image: postgres:11.6
    container_name: altiore_postgres
    restart: always
    volumes:
      - postgres-altiore:/docker-entrypoint-initdb.d
      - postgres-altiore:/usr/bin/wait-postgres
    environment:
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - POSTGRES_TEST_DB=${POSTGRES_TEST_DB}
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
    ports:
      - ${TYPEORM_PORT}:5432

volumes:
  postgres-altiore:
  redis-altiore:
